spring:
  application:
    name: hello-spring-cloud-web-admin-feign

server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
foo: foo version 1
#   解决在多个feign接口中定义相同的服务名
#    main:
#      allow-bean-definition-overriding: true

